### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wanghengheng** [mogulanyang/LYMagicMacro#1]
1. 建议所有宏统一加一个 ly 前缀 - 在 ide 的环境下用起来会更好找一点，也避免与 apple 原生库发生可能的命名冲突

2. 建议宏命名方式统一下划线或者驼峰；或者是提倡使用的用驼峰，非提倡的用下划线 - 目前有些变量是下划线驼峰混用

3. 建议把 base 类的宏，提到某一部分的顶部 - 方便阅读，和拷贝

4. 看到 DEBUG 那里直接把系统的 NSLog 方法重定义了，不知道这样会不会不太好

从作者这里学了不少宏的玩法。。谢！

**Comment by mogulanyang** [comment]
收到!WangHengHeng童鞋的意见非常宝贵,谢谢您~
不过呀,
1.对于驼峰,我觉得宏毕竟是宏,我希望他还是有宏的下划线的样子,如果做得太像方法容易有迷惑性.我害怕大家会以为是个方法.

2.另外,我仅仅是把方法里面的参数前缀加了ly,目的是为了防止宏中参数重名引用.其实我希望的是尽可能简单,不希望我因为我的前缀干扰到用户的体验,看起来也工整一点.

3.有关Base类的宏,当时我想的是不需要大伙儿去关注base类的宏,直接使用就可以,放在顶部的宏是大家平时比较常用的,如果忘记,可以跳进来看看.

4.另外关于NSLog,我会考虑把它更改一下,如果你觉得有点难用,先暂时把它删掉吧!
另外对于宏,我觉得是一个特别有趣的东西,看见有人喜欢我觉得自己的分享就值了~
